### ISSUE TITLE
No option to save patterns to drive

### ISSUE THREAD

**Issue by ZenithRogue** [copy/life#1]
Would you be able to add an option to save a pattern to your drive for later loading?

**Comment by copy** [comment]
Indeed, that would be most reasonable.

Note, if you want to download the original pattern file, you can do so by clicking on the pattern name on the bottom left and then find the link there.

**Comment by copy** [comment]
This feature is now available under "export" on the main screen. Let me know if this works for you.

**Comment by ZenithRogue** [comment]
Perfect! Thanks
